module.exports = [
	'Single',
	'Double',
	'Triple',
	'Quad',
	'Queen',
	'King',
	'Twin',
	'Hollywood Twin Room',
	'Double-double',
	'Studio',
	'Suite / Executive Suite',
	'Mini Suite or Junior Suite',
	'President Suite | Presidential Suite',
	'Apartments / Room for Extended Stay',
	'Connecting rooms',
	'Murphy Room',
	'Accessible Room / Disabled Room',
	'Cabana',
	'Adjoining rooms',
	'Adjacent rooms',
	'Villa',
	'Executive Floor/Floored Room',
	'Smoking / Non-Smoking Room',
];
